title: ДК с.Выгода
author:
  name: Eugene Nikulesku
  email: 'nikulesku@ukr.net'
blog:
  route: ''
metadata:
    description: 'Основными задачами Дома Культуры являются развитие самодеятельного народного творчества, раскрытия творческих способностей и дарований людей, сохранение, возрождение и развитие культуры, поддержка талантливой и одаренной молодежи.'


